import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "./session-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <nav className="flex p-2 bg-gray-400 w-full gap-10 ">
            <a href="/">home</a>
            <a href="/users">User</a>
            <a href="/login">Login</a>
            <a href="/register">Register</a>
            <a href="/admin">Admin</a>
          </nav>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
